const scobyProductPath = '/proizvodi/kombuha-scoby-cajna-gljiva';

export const tutorialPages = {
    preparation: {
        pathname: '/uputstva/priprema-kombuhe',
        image: '/images/priprema-kombuhe-korak6.png',
        totalTime: 'PT7D',
        estimatedCost: {
            '@type': 'MonetaryAmount',
            currency: 'RSD',
            value: '1000',
        },
        supplies: ['SCOBY kultura', 'Crni ili zeleni čaj', 'Šećer', 'Voda'],
        tools: ['Staklena tegla', 'Šerpa ili džezva', 'Pamučna prekrivka'],
        showRelated: true,
        showTeamSection: true,
        locales: {
            sr: {
                title: 'Kako se pravi kombuha - uputstvo pripreme kombuhe kod kuće',
                seoTitle: 'Kako se pravi kombuha - uputstvo pripreme kombuhe kod kuće',
                description:
                    'Saznajte kako se pravi kombuha čaj kod kuće. Uputstvo i recept za pripremu kombucha čajna gljiva napitka. bucha.rs Srbija',
                keywords: 'kako se pravi kombuha, priprema kombuhe, kombuha recept, kombuha kod kuće, scoby uputstvo',
                intro: {
                    title: 'Kombuha uputstvo za pripremu',
                    text1: {
                        textBefore: 'Ovo uputstvo obuhvata sve korake kako da od tek otpakovanog ',
                        linkText: 'Scoby-a',
                        href: scobyProductPath,
                        textAfter:
                            ' (čajne gljive koju ste kupili) dođete do vaše prve domaće kombuhe. Tako da, ukoliko još uvek nemate svoju specijalnu gljivu, prvo',
                    },
                    link: '/prodaja',
                    linkText: ' poručite kombuha gljivu preko linka ',
                    text2: 'pa se vratite na ovo uputstvo, ono neće nigde otići. E, super, sada još osmeh na lice i imate sve što vam je potrebno. Priprema kombuhe je zaista jednostavan proces i vrlo brzo ćete se uhodati. Spremni? Krećemo! 🥳',
                },
                steps: [
                    {
                        number: '1',
                        title: 'Pripremite teglu',
                        text: 'Zdrava Scoby jedinka (čajna gljiva) za oko nedelju dana može da proizvede, zavisno od veličine, između 2 i 8 litara kombuha baze. Iako mlad, Scoby kojeg ste dobili od nas u “Starter” setu može da proizvede oko 2 litre pića. Scoby će svakom novom turom rasti i biće spreman da proizvodi sve više kombuhe, tako da držite to na umu. Takođe, dužina prve fermentacije može da varira od 5-6 dana ukoliko želite slabiji ukus, pa sve do 2 nedelje ukoliko želite intenzivniji ukus kombuhe, za početak se držite naše preporuke od 7 dana pa korigujte po svom ukusu. Sada kada ovo znate, detaljno operite staklenu teglu koju ste dobili u setu, ili koju ste pripremili, postavite je na radnu površinu i pređite na naredni korak.',
                        image: '/images/priprema-kombuhe-korak1.png',
                        order: '1',
                    },
                    {
                        number: '2',
                        title: 'Prokuvajte vodu za čaj',
                        text: 'Naredni korak je da sipate oko 2l vode u šerpicu ili džezvu i da je stavite na vatru da prokuva. Dok čekate da voda proključa, pređite na korak 3.',
                        image: '/images/priprema-kombuhe-korak2.png',
                        order: '2',
                    },
                    {
                        number: '3',
                        title: 'Spremite čaj',
                        text: 'Za pripremu kombuhe koristite isključivo zeleni ili crni čaj. Mi smo eksperimentisali sa mnogim drugim opcijama (nana, kamilica, želfija itd.), ali smo videli da gljiva najbolje uspeva sa zelenim ili crnim čajem. Mi za našu kombuhu uvek koristimo rinfuzni čaj pošto je čistiji, ali ukoliko imate samo čaj u kesicama i to je skroz okej. Koristite zeleni čaj ako više volite sladunjav ukus, dok je crni čaj bolji ukoliko više volite gorke note. Biće vam potrebno 4 grama čaja po litri kombuhe koju pravite, tako da ako imate teglu od 2 litre, treba vam 8 grama čaja.',
                        image: '/images/priprema-kombuhe-korak3.png',
                        order: '1',
                    },
                    {
                        number: '4',
                        title: 'Završite osnovu',
                        text: 'Nakon što voda proključa, sipajte je u teglu, zatim u vodu stavite čaj koji ste pripremili i sačekajte 4 do 10 minuta da se čaj napravi.',
                        image: '/images/priprema-kombuhe-korak4.png',
                        order: '2',
                    },
                    {
                        number: '5',
                        title: 'Dodajte šećer',
                        text: 'Naredni korak je da našem Scoby-u pripremimo hranu. Scoby se hrani šećerom, tako da će nakon prve fermentacije gotovo sav šećer koji sada dodate, nestati (Scoby će ga razgraditi). Potrebno je da u čaj sipate 60 grama šećera po litri kombuhe koju pripremate. Ukoliko imate teglu od 2 litre, biće vam potrebno 120 grama šećera. Koristite isključivo beli šećer. Mi za našu fermentaciju koristimo beli trščani šećer, ali i običan kristal šećer je skroz okej, samo je bitno da bude beli, a ne smeđi, pošto Scoby samo taj može da razgradi. Nakon što ste dodali šećer u teglu, dobro ga promešajte da se potpuno rastvori.',
                        image: '/images/priprema-kombuhe-korak5.png',
                        order: '1',
                    },
                    {
                        number: '6',
                        title: 'Zagnjurite Scoby-a',
                        text: 'Kada se čaj ohladi na sobnu temperaturu, dodajte u njega glavnog glumca ove predstave. Nikako Scoby-a ne stavljajte u vruću vodu pošto ćete ga spržiti, a on je, na kraju krajeva, malo ljigavo, ali na neki način veoma drago živo biće. Uz gljivu u našem setu ste dobili i “starter” tečnost koju takođe u potpunosti treba da sipate u teglu. Ona je zadužena da započne proces fermentacije, obezbedi odgovarajuću pH vrednost i bez nje vaš Scoby može da... kako da kažem... ode na produženi odmor. U svakoj narednoj turi ostavite oko jednu šolju (250-330ml) baze sa strane pa je, kao i sada, dodajte na kraju uz samu gljivu. Još jedan savet, pre svake nove ture u mlakoj vodi blago properete Scoby-a. Higijena je kod pripreme kombuhe veoma važna stvar i uvek obratite pažnju da sa čajnom gljivom rukujete čistim rukama. Scoby jeste gljiva i pojava sluzi, neprijatnih mirisa, mrkih fleka ili novih delova je skroz normalna. Jedino što treba da vas zabrine je pojava plavih tačkica ili buđi, u tom slučaju ih što pre otklonite ili cela kombuha može propasti. Sada prekrite teglu pamučnom prekrivkom kako bi kombuha mogla da diše i to je manje više to. Ukoliko ste uspešno ispratili sve korake do sada, ostaje vam samo da se pozdravite sa Scoby-em do sledeće nedelje i da teglu odložite na mračno i suvo mesto. Znamo da je zanimljivo da svaki dan obilazite i pratite kako vaša mala fabrika napreduje, ali pazite da time ne poremetite njen rad. Sada ste zvanično kombuha majstori!',
                        image: '/images/priprema-kombuhe-korak6.png',
                        order: '2',
                    },
                    {
                        number: '7',
                        title: 'Šta dalje?',
                        text: 'Znamo da je mnogima ovo prvi put da prave kombuhu, zato pretpostavljamo da imate još gomilu pitanja za nas 😄. Pokušali smo da na što više njih damo odgovor, bacite pogled:',
                        order: '1',
                        links: [
                            '/uputstva/koliko-kombuhe-treba-piti',
                            '/uputstva/kako-se-cuva-kombuha',
                            '/uputstva/da-li-kombuha-sadrzi-alkohol',
                        ],
                        linkTexts: [
                            'Koliko kombuhe treba piti?',
                            'Kako se čuva kombuha?',
                            'Da li kombuha sadrži alkohol?',
                        ],
                        textAfter: ' i još mnoge druge teme koje možete pronaći na dnu stranice.',
                    },
                ],
            },
            en: {
                title: 'How to make kombucha at home',
                seoTitle: 'How to make kombucha at home | Step-by-step guide',
                description:
                    'Learn how to make kombucha at home with a simple step-by-step guide for your first batch, from tea base to SCOBY fermentation.',
                keywords: 'how to make kombucha, kombucha recipe, home brewing kombucha, scoby starter guide',
                intro: {
                    title: 'Kombucha brewing guide',
                    text1: {
                        textBefore: 'This tutorial takes you from an unboxed ',
                        linkText: 'SCOBY culture',
                        href: scobyProductPath,
                        textAfter: ' to your first successful batch. If you still need a starter culture, ',
                    },
                    link: '/prodaja',
                    linkText: 'order one here',
                    text2: ' and then come back to the steps below. The process is straightforward and becomes much easier after the first run.',
                },
                steps: [
                    {
                        number: '1',
                        title: 'Prepare the jar',
                        text: 'Wash the glass jar thoroughly and prepare a clean work surface. A young SCOBY from a starter kit usually handles around two liters per batch and will keep getting stronger over time.',
                        image: '/images/priprema-kombuhe-korak1.png',
                        order: '1',
                    },
                    {
                        number: '2',
                        title: 'Boil water for tea',
                        text: 'Heat about one liter of water. You will top the jar up with cold water later, so there is no need to boil the full volume immediately.',
                        image: '/images/priprema-kombuhe-korak2.png',
                        order: '2',
                    },
                    {
                        number: '3',
                        title: 'Choose and brew the tea',
                        text: 'Start with black or green tea. Use about four grams of tea per liter. Black tea gives a fuller profile, while green tea tastes lighter and fresher.',
                        image: '/images/priprema-kombuhe-korak3.png',
                        order: '1',
                    },
                    {
                        number: '4',
                        title: 'Finish the tea base',
                        text: 'Pour the hot water over the tea and let it steep for a few minutes, just as you would when preparing regular tea.',
                        image: '/images/priprema-kombuhe-korak4.png',
                        order: '2',
                    },
                    {
                        number: '5',
                        title: 'Add sugar',
                        text: 'Add about 60 grams of sugar per liter. The sugar feeds the culture during fermentation and most of it is consumed while the kombucha matures.',
                        image: '/images/priprema-kombuhe-korak5.png',
                        order: '1',
                    },
                    {
                        number: '6',
                        title: 'Add the SCOBY and starter liquid',
                        text: 'Make sure the tea has cooled to room temperature and then place the SCOBY into the jar together with all the starter liquid. Never place a SCOBY into hot liquid. Cover the jar with a breathable cloth, keep it in a dark dry place and let it ferment for about seven days.',
                        image: '/images/priprema-kombuhe-korak6.png',
                        order: '2',
                    },
                    {
                        number: '7',
                        title: 'What comes next?',
                        text: 'Once the first fermentation is done, you can move on to flavoring, or continue with our guides about safe consumption and health benefits.',
                        order: '1',
                        links: [
                            '/uputstva/koliko-kombuhe-treba-piti',
                            '/uputstva/kako-se-cuva-kombuha',
                            '/uputstva/da-li-kombuha-sadrzi-alkohol',
                        ],
                        linkTexts: [
                            'How much kombucha should you drink?',
                            'How to store kombucha?',
                            'Does kombucha contain alcohol?',
                        ],
                    },
                ],
            },
            ru: {
                title: 'Как приготовить комбучу дома',
                seoTitle: 'Как приготовить комбучу дома | Пошаговое руководство',
                description:
                    'Пошаговое руководство по приготовлению комбучи дома: от чайной основы до первой ферментации со SCOBY.',
                keywords: 'как приготовить комбучу, рецепт комбучи, комбуча дома, scoby инструкция',
                intro: {
                    title: 'Руководство по приготовлению комбучи',
                    text1: {
                        textBefore: 'Этот материал проведет вас от распаковки ',
                        linkText: 'SCOBY',
                        href: scobyProductPath,
                        textAfter: ' до первой удачной партии. Если стартовой культуры у вас еще нет, ',
                    },
                    link: '/prodaja',
                    linkText: 'закажите ее здесь',
                    text2: ', а затем возвращайтесь к шагам ниже. Сам процесс несложный и после первой ферментации становится гораздо понятнее.',
                },
                steps: [
                    {
                        number: '1',
                        title: 'Подготовьте банку',
                        text: 'Тщательно вымойте стеклянную банку и подготовьте чистую рабочую поверхность. Молодой SCOBY из стартового набора обычно подходит для двух литров за одну партию и со временем становится сильнее.',
                        image: '/images/priprema-kombuhe-korak1.png',
                        order: '1',
                    },
                    {
                        number: '2',
                        title: 'Вскипятите воду для чая',
                        text: 'Нагрейте около одного литра воды. Остальной объем вы позже добавите холодной водой, поэтому кипятить сразу всю жидкость не нужно.',
                        image: '/images/priprema-kombuhe-korak2.png',
                        order: '2',
                    },
                    {
                        number: '3',
                        title: 'Заварите чай',
                        text: 'Для начала используйте черный или зеленый чай. Нужны примерно четыре грамма чая на литр. Черный чай дает более насыщенный вкус, зеленый - более легкий и свежий.',
                        image: '/images/priprema-kombuhe-korak3.png',
                        order: '1',
                    },
                    {
                        number: '4',
                        title: 'Подготовьте чайную основу',
                        text: 'Залейте чай горячей водой и дайте ему настояться несколько минут, как при обычном заваривании.',
                        image: '/images/priprema-kombuhe-korak4.png',
                        order: '2',
                    },
                    {
                        number: '5',
                        title: 'Добавьте сахар',
                        text: 'Добавьте около 60 граммов сахара на литр. Сахар нужен культуре во время ферментации, и большая его часть будет переработана по мере созревания напитка.',
                        image: '/images/priprema-kombuhe-korak5.png',
                        order: '1',
                    },
                    {
                        number: '6',
                        title: 'Добавьте SCOBY и стартовую жидкость',
                        text: 'Поместите SCOBY в банку и влейте всю стартовую жидкость. Накройте банку дышащей тканью, поставьте в темное сухое место и оставьте примерно на семь дней.',
                        image: '/images/priprema-kombuhe-korak6.png',
                        order: '2',
                    },
                    {
                        number: '7',
                        title: 'Что дальше?',
                        text: 'После первой ферментации можно переходить к ароматизации или продолжить чтение наших материалов о безопасном употреблении и пользе комбучи.',
                        order: '1',
                        links: [
                            '/uputstva/koliko-kombuhe-treba-piti',
                            '/uputstva/kako-se-cuva-kombuha',
                            '/uputstva/da-li-kombuha-sadrzi-alkohol',
                        ],
                        linkTexts: [
                            'Сколько комбучи можно пить?',
                            'Как хранить комбучу?',
                            'Содержит ли комбуча алкоголь?',
                        ],
                    },
                ],
            },
        },
    },
    secondFermentation: {
        pathname: '/uputstva/druga-fermentacija',
        image: '/images/kombuha_druga_fermentacija_korak1.png',
        totalTime: 'PT4D',
        estimatedCost: {
            '@type': 'MonetaryAmount',
            currency: 'RSD',
            value: '1000',
        },
        supplies: ['Kombuha baza iz prve fermentacije', 'Voće ili začini po izboru', 'Flaše sa zatvaračem'],
        tools: ['Flaša sa hermetičkim čepom', 'Nož', 'Daska za sečenje'],
        showRelated: false,
        showTeamSection: true,
        locales: {
            sr: {
                title: 'Kombuha druga fermentacija - uputstvo za pripremu ukusa',
                seoTitle: 'Kombuha druga fermentacija - uputstvo za pripremu ukusa',
                description:
                    'Detaljan recept za pravljenje kombuha čaja sa različitim ukusima voća. Druga fermentacija je proces u kom kombuha napitak od čajne gljive dobija sjajan ukus.',
                keywords:
                    'druga fermentacija kombuhe, kombuha sa ukusima, hibiskus kombuha, đumbir kombuha, karbonizacija kombuhe',
                intro: {
                    title: 'Kombuha ukusi - uputstvo za drugu fermentaciju',
                    text1: 'Ukoliko ste završili sa pripremom baze i spremni ste da kombuhu obogatite sjajnim ukusima, onda ste na pravom mestu. Ukoliko ne znate o čemu pričam, onda prvo pogledajte',
                    link: '/uputstva/priprema-kombuhe',
                    linkText: ' uputstvo za pripremu kombuhe',
                    text2: '. Druga fermentacija je “where magic happens”. Ovde od relativno nezanimljive baze, kreiramo sjajne ukuse i domaće gazirane sokove koji su veoma osvežavajući za piće. Tako da, ukoliko želite da učinite vašu kombuhu zabavnom, skoknite na korak 1.',
                },
                steps: [
                    {
                        number: '1',
                        title: 'Pripremite sastojke',
                        text: 'Došao je trenutak koji ste čekali. Prva fermentacija, kako je zovemo, se završila. Vaša mala fabrika u tegli je naporno radila i sada možete da pređete na drugu fermentaciju i obogatite kombuhu različitim ukusima. Ovaj korak nije obavezan i, ukoliko vam je osnovna kombuha ukusna i odgovarajuća, onda ste na konju, ali ako ste kao mi i želite malo šareniju, voćniju, zanimljiviju kombuhu, flaširanjem i dodavanjem voća možete da u svojoj kući pripremite prelep sok. Izvadite teglu sa kombuhom i stavite je na radnu površinu. Zatim odlučite koji ukus želite da pravite i nabavite to voće ili čajeve. Ukoliko ste novi u ovome, pređite na korak 2 da čujete neke naše ideje.',
                        image: '/images/kombuha_druga_fermentacija_korak1.png',
                        order: '1',
                    },
                    {
                        number: '2',
                        title: 'Odaberite ukus',
                        text: 'Za drugu fermentaciju kombuhe možete da koristite gotovo svo voće, povrće i čajeve, ali prosto neki ukusi nisu baš najsrećniji. Za početak možete da isprobate neke naše proverene recepte, a u narednoj turi slobodno i sami eksperimentišete sa novim idejama. Jedan od naših najpopularnijih ukusa je Hibiskus + Đumbir. Za njegovu pripremu potrebno vam je 10 grama rinfuznog hibiskus čaja po flaši, parče đumbira od 10 do 20 grama i jedan limun. Prvo nacedite limun, sipajte ga u flašu sa hermetičkim čepom u kojoj ćete vršiti drugu fermentaciju, zatim ubacite rinfuzni hibiskus i na kraju naseckajte đumbir na sitne kockice i dodajte ih u flašu. Proces je sličan za bilo koji ukus koji pravite, a spisak svih naših recepata možete pogledati na linku ',
                        image: '/images/kombuha_druga_fermentacija_korak2.png',
                        links: ['#'],
                        linkTexts: ['kombuha recepti.'],
                        order: '2',
                    },
                    {
                        number: '3',
                        title: 'Sipajte kombuha bazu',
                        text: 'Naredni korak je da sipate kombuha bazu iz prve fermentacije u flašu maltene do vrha, ostavljajući vrlo malo prostora do čepa. Zatvorite hermetički čep pažljivo i to je to, odradili ste sve što je potrebno za uspešnu drugu fermentaciju. U narednih 3 do 4 dana u flaši će se vršiti karbonizacija i kombuha će pretvoriti šećer iz voća u gazirani napitak zbog kog smo i započeli ovu zanimljivu avanturu. Nakon što ste pričekali 3 do 4 dana da se završi druga fermentacija, najbolje bi bilo da odložite flaše u frižider preko noći. Time ćete zaustaviti proces karbonizacije i samim tim sebi olakšati otvaranje kombuhe sledećeg dana. Kada to uradite, spremni ste da pređete na korak 4.',
                        image: '/images/kombuha_druga_fermentacija_korak3.png',
                        order: '1',
                    },
                    {
                        number: '4',
                        title: 'Otvaranje flaše',
                        text: 'Iako sada verovatno razmišljate: “Joj, Bože, šta ima da me uče kako da otvorim flašu, samo uzmem i otvorim...”, verujte mi, ovo je jako bitan deo. Samo se setite da su se u zatvorenoj flaši u prethodnih par dana stvorili ugljen-dioksid i mehurići i da ćete, ako naglo otvorite flašu, dobiti fenomenalnu eksploziju, kao kada promućkate Coca-Colu. Zato otvarajte flašu veoma oprezno. Verovatno će se kreirati veliki pritisak na čepu i biće teško da je polako otvorite, ali budite strpljivi. Takođe, odmah da vas upozorimo, gotovo sigurno ćete prebrzo otvoriti flašu prvi put i verovatno će vam kombuha napraviti nered po celoj kuhinji, tako da, kada krenete da nam ... sve po spisku, samo se setite da smo vas upozorili. Ukoliko se kombuha previše karbonizovala tokom druge fermentacije, naredni put smanjite broj dana, ukoliko želite da bude gaziranije, stavite više đumbira i sačekajte dan, dva duže.',
                        image: '/images/kombuha_druga_fermentacija_korak4.png',
                        order: '2',
                    },
                    {
                        number: '5',
                        title: 'Uživajte i eksperimentišite',
                        text: 'Ukoliko je sve prošlo kako treba, uspeli ste: napravili ste vašu prvu super sjajnu bajnu kombuhu. Čestitamo! Nadamo se da ste uživali, da su vam naša uputstva pomogla i da ste naučili nešto novo. Sada je red na vas da budete kreativni i da eksperimentišete sa dužinom trajanja faza i različitim ukusima. Sigurni smo da ćete pronaći pravu kombinaciju ukusa koja vama odgovara. Sve vaše eksperimente podelite sa nama uz hashtag #buchars i podelićemo vaše rezultate na našim društvenim mrežama. Podelite pozitivnu energiju i videćete kako se osmeh pojavljuje na licima ljudi u vašoj okolini. Puno sreće u daljem igranju želi vam bucha.rs tim.',
                        image: '/images/kombuha_druga_fermentacija_korak5.png',
                        order: '1',
                    },
                ],
            },
            en: {
                title: 'Kombucha second fermentation guide',
                seoTitle: 'Kombucha second fermentation guide | Flavoring and carbonation',
                description:
                    'A detailed guide to kombucha second fermentation, flavor additions and natural carbonation at home.',
                keywords: 'kombucha second fermentation, flavoring kombucha, kombucha carbonation, kombucha flavors',
                intro: {
                    title: 'Kombucha flavors - second fermentation guide',
                    text1: 'If your first fermentation is finished and you want to turn the base into a lively, fruity and sparkling drink, this is the next step. If you need the first stage first, check the ',
                    link: '/uputstva/priprema-kombuhe',
                    linkText: 'kombucha brewing guide',
                    text2: '. Second fermentation is where the base develops personality flavor and fun.',
                },
                steps: [
                    {
                        number: '1',
                        title: 'Prepare your ingredients',
                        text: 'Take out the base from the first fermentation and decide which flavor profile you want. Fruit, spices and herbal teas all give different results.',
                        image: '/images/kombuha_druga_fermentacija_korak1.png',
                        order: '1',
                    },
                    {
                        number: '2',
                        title: 'Choose the flavor combination',
                        text: 'One reliable combination is hibiscus with ginger and lemon. Add the chosen ingredients directly to the bottle where the second fermentation will happen.',
                        image: '/images/kombuha_druga_fermentacija_korak2.png',
                        order: '2',
                    },
                    {
                        number: '3',
                        title: 'Fill the bottle with kombucha base',
                        text: 'Pour the kombucha base in until the bottle is almost full, leaving a little room for pressure. Seal it tightly and leave it at room temperature for a few days.',
                        image: '/images/kombuha_druga_fermentacija_korak3.png',
                        order: '1',
                    },
                    {
                        number: '4',
                        title: 'Open carefully',
                        text: 'After three to four days, chill the bottle overnight and open it slowly. Second fermentation builds pressure and the carbonation can be strong.',
                        image: '/images/kombuha_druga_fermentacija_korak4.png',
                        order: '2',
                    },
                    {
                        number: '5',
                        title: 'Enjoy and keep experimenting',
                        text: 'Once you find a fermentation time and flavor combination that works for you, write it down and continue testing new combinations.',
                        image: '/images/kombuha_druga_fermentacija_korak5.png',
                        order: '1',
                    },
                ],
            },
            ru: {
                title: 'Руководство по второй ферментации комбучи',
                seoTitle: 'Вторая ферментация комбучи | Вкусы и естественная газированность',
                description:
                    'Подробное руководство по второй ферментации комбучи, добавлению вкусов и получению естественной газированности дома.',
                keywords: 'вторая ферментация комбучи, вкусы комбучи, газированность комбучи, ароматизация комбучи',
                intro: {
                    title: 'Вкусы комбучи - руководство по второй ферментации',
                    text1: 'Если первая ферментация уже завершена и вы хотите превратить базу в яркий, фруктовый и газированный напиток, следующий шаг здесь. Если сначала нужна первая стадия, посмотрите ',
                    link: '/uputstva/priprema-kombuhe',
                    linkText: 'руководство по приготовлению комбучи',
                    text2: '. Именно во второй ферментации напиток получает характер и аромат.',
                },
                steps: [
                    {
                        number: '1',
                        title: 'Подготовьте ингредиенты',
                        text: 'Достаньте базу после первой ферментации и решите, какой вкус хотите получить. Фрукты, специи и травяные чаи дают очень разные результаты.',
                        image: '/images/kombuha_druga_fermentacija_korak1.png',
                        order: '1',
                    },
                    {
                        number: '2',
                        title: 'Выберите вкусовую комбинацию',
                        text: 'Одна из самых надежных комбинаций - гибискус, имбирь и лимон. Добавьте выбранные ингредиенты прямо в бутылку для второй ферментации.',
                        image: '/images/kombuha_druga_fermentacija_korak2.png',
                        order: '2',
                    },
                    {
                        number: '3',
                        title: 'Заполните бутылку базой комбучи',
                        text: 'Налейте базу почти до верха, оставив немного места для давления. Плотно закройте бутылку и оставьте ее на несколько дней при комнатной температуре.',
                        image: '/images/kombuha_druga_fermentacija_korak3.png',
                        order: '1',
                    },
                    {
                        number: '4',
                        title: 'Открывайте осторожно',
                        text: 'Через три-четыре дня поставьте бутылку в холодильник на ночь и открывайте медленно. Во время второй ферментации образуется заметное давление.',
                        image: '/images/kombuha_druga_fermentacija_korak4.png',
                        order: '2',
                    },
                    {
                        number: '5',
                        title: 'Пробуйте и экспериментируйте',
                        text: 'Когда вы найдете подходящее время ферментации и любимую комбинацию вкусов, запишите ее и продолжайте пробовать новые варианты.',
                        image: '/images/kombuha_druga_fermentacija_korak5.png',
                        order: '1',
                    },
                ],
            },
        },
    },
};
